baseURL: https://bardhansubhankar02.github.io
languageCode: en-us
title: Notre-Dame de Paris
theme: ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ""
enableRobotsTXT: true

languages:
  en:
    title: Ananke
    weight: 1
    contentDir: content/en
params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  description: The last theme you'll ever need. Maybe.
  background_color_class: bg-black
  recent_posts_number: 3
  ananke_socials:
    - name: twitter
      url: https://twitter.com
