baseURL: https://bardhansubhankar02.github.io
languageCode: en-us
title: Subhankar Bardhan
theme: ananke
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 5
googleAnalytics: ""
enableRobotsTXT: true

languages:
  en:
    title: Subhankar Bardhan
    weight: 1
    contentDir: content/
params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  # description: The last theme you'll ever need. Maybe.
  background_color_class: bg-black
  recent_posts_number: 3
  math: true
  ananke_socials:
    - name: twitter
      url: https://twitter.com
